#!/bin/sh

hsetroot -fill /usr/share/wallpapers/wallpaper.png

INIFILE=/ventoy/Ventoy2Disk.ini

echo "[Ventoy]"                                 >> $INIFILE
echo "Language=Chinese Simplified (简体中文)"   >> $INIFILE
echo "PartStyle=0"                              >> $INIFILE
echo "ShowAllDevice=0"                          >> $INIFILE

/ventoy/tool/x86_64/Ventoy2Disk.gtk3 --kiosk

